---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.5

suites:
  - name: default
    driver:
       network:
       - ["private_network", {ip: "192.168.11.22"}]
    run_list:
      - recipe[nginx::default]
    attributes:
