name 'apache-softtek'
maintainer 'Ulises Escareño, Diego De Fuentes'
maintainer_email 'ulises.escareno@softtek.com'
maintainer_email 'diego.fuentes@softtek.com'
license 'all_rights'
description 'Installs/Configures apache3'
long_description 'Installs/Configures apache3'
version '0.1.0'
